### PR TITLE
Update 2015-03-16-bath-ruby.markdown

### PR DESCRIPTION
**Pull request by despo**
Opening Rosa's PR. :+1: 

Happy to have mine dropped - the css should resolve the expanding image problem.

### CODE REVIEW

**Comment by matyikriszta** [comment]
Ok, this is done, I think it's in a good place, shall we post it tomorrow?

**Comment by despo** [comment]
@matyikriszta yes. Do you want to specify your email as well at `author_email` so it gets utilised when I merged into master.

**Comment by despo** [comment]
@matyikriszta and change the date!

**Comment by matyikriszta** [comment]
done and done!

**Comment by despo** [comment]
Ok. Shall i just deploy it then, and we can tweet tomorrow? @matyikriszta

**Comment by matyikriszta** [comment]
Yes, I think that's ok :)

**Pull request merged**
